# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = ['drv_uart.c', 'drv_pin.c']

if GetDepend('BSP_USING_DIRECT_UART'):
    src += ['direct_uart.c']

if GetDepend('BSP_USING_I2C'):
    src += ['drv_i2c.c']

if GetDepend('BSP_USING_AVS'):
    src += ['drv_avs.c']

if GetDepend('BSP_USING_HWTIMER0') or GetDepend('BSP_USING_HWTIMER1'):
    src += ['drv_hwtimer.c']

if GetDepend('BSP_USING_WDT'):
    src += ['drv_wdt.c']

if GetDepend('BSP_USING_PWM'):
    src += ['drv_pwm.c']

if GetDepend('BSP_USING_RTC'):
    src += ['drv_rtc.c']

if GetDepend('BSP_USING_LCD'):
    src += ['drv_lcd.c', 'drv_disp2.c']

CPPPATH = [cwd]

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

objs = [group]

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
